Listing 5.1: Example of creating one-dimensional array.

In [1]:
# create one-dimensional array
from numpy import array
# list of data
data = [11, 22, 33, 44, 55]
# array of data
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


Listing 5.3: Example of creating two-dimensional array.

In [ ]:
# create two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


Listing 5.5: Example of indexing a one-dimensional array.

In [ ]:
# index a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[0])
print(data[4])

11
55


Listing 5.7: Example of an error when indexing a one-dimensional array.

In [ ]:
# index array out of bounds
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[5])

IndexError: ignored

Listing 5.9: Example of negative indexing a one-dimensional array.

In [ ]:
# negative array indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[-1])
print(data[-5])

55
11


Listing 5.13: Example of indexing a two-dimensional array.

In [ ]:
# index two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,0])

11


Listing 5.15: Example of indexing the First column of a two-dimensional array.

In [ ]:
# index row of two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,])

[11 22]


Listing 5.18: Example of slicing a one-dimensional array. data[from:to]

In [ ]:
# slice a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[:])

[11 22 33 44 55]


Listing 5.20: Example of slicing a subset of a one-dimensional array.

In [ ]:
# slice a subset of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[0:1])

[11]


Listing 5.22: Example of slicing with a negative index on a one-dimensional array.

In [ ]:
# negative slicing of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


Listing 5.26: Example of slicing a dataset into input and output variables.

In [ ]:
# split input and output data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
X= data[:, :-1]
print(X)


[[11 22]
 [44 55]
 [77 88]]


Listing 5.30: Example of slicing a dataset into train and test subsets

In [2]:
# split train and test data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


Listing 5.32: Example of accessing shape for a one-dimensional array

In [3]:
# shape of one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


Listing 5.34: Example of accessing shape for a two-dimensional array.

In [4]:
# shape of a two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)

(3, 2)


Listing 5.36: Example of accessing shape for a two-dimensional array in terms of rows and
columns.

In [5]:
# row and column shape of two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
        [33, 44],
[55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


Listing 5.39: Example of changing the shape of a one-dimensional array with the reshape()
function.

In [6]:
# reshape 1D array to 2D
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)

(5,)
(5, 1)


Listing 5.42: Example of changing the shape of a two-dimensional array with the reshape()
function.

In [7]:
# reshape 2D array to 3D
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
(3, 2, 1)
