Listing 4.1: Example of creating an array with the array() function.

In [1]:
# create array
from numpy import array

In [2]:
# create array
l = [1.0, 2.0, 3.0]
a = array(l)
# display array
print(a)
# display array shape
print(a.shape)
# display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


Listing 4.3: Example of creating an array with the empty() function.

In [4]:
# create empty array
from numpy import empty
a = empty([3,3])
print(a)

[[3.88145876e-316 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


Listing 4.5: Example of creating an array with the zeros() function.

In [5]:
# create zero array
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Listing 4.7: Example of creating an array with the ones() function.

In [7]:
# create one array
from numpy import ones
a = ones([9])
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


Listing 4.9: Example of creating an array from other arrays using the vstack() function.

In [8]:
# create array with vstack
from numpy import array
from numpy import vstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


Listing 4.11: Example of creating an array from other arrays using the hstack() function.

In [1]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# create horizontal stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)
